title: My example Github Pages
author: Nathan Laing
email: ktmlaing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A GitHub Page for the GitHub Learning Labs course

# social links
twitter_username: Nathan__Laing
github_username:  Charybdiss

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
